/*
 * Copyright (C) 2025 Stephen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.steeviebops.hacktvgui;

import java.awt.Cursor;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen
 */
public class DownloadButtonDialogue extends javax.swing.JDialog {
    
    private String selection;

    /**
     * Creates new form DownloadButtonDialogue
     * @param parent
     * @param modal
     */
    public DownloadButtonDialogue(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.setLocationRelativeTo(parent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        downloadPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnfsphil = new javax.swing.JButton();
        btnCaptainJack = new javax.swing.JButton();
        btninaxeon = new javax.swing.JButton();
        lblfsphil1 = new javax.swing.JLabel();
        lblfsphil2 = new javax.swing.JLabel();
        lblCaptainJack1 = new javax.swing.JLabel();
        lblCaptainJack2 = new javax.swing.JLabel();
        lblinaxeon1 = new javax.swing.JLabel();
        lblinaxeon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download hacktv for Windows");
        setResizable(false);

        downloadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("hacktv download options"));

        lblHeader.setText("<html>Please select the hacktv build to download.<br>These files are hosted on an automated build server run by the author.</html>");

        btnfsphil.setText("fsphil");
        btnfsphil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfsphilActionPerformed(evt);
            }
        });

        btnCaptainJack.setText("Captain Jack");
        btnCaptainJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptainJackActionPerformed(evt);
            }
        });

        btninaxeon.setText("Matt's TV Barn");
        btninaxeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninaxeonActionPerformed(evt);
            }
        });

        lblfsphil1.setText("<html>This is the original hacktv build.<br>Recommended for most use cases.</html>");

        lblfsphil2.setText("<html><a href=\"https://github.com/fsphil/hacktv\">https://github.com/fsphil/hacktv</a></html>");
        lblfsphil2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfsphil2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfsphil2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblfsphil2MouseExited(evt);
            }
        });

        lblCaptainJack1.setText("<html>A hacktv fork with additional features and an emphasis on video scrambling.</html>");

        lblCaptainJack2.setText("<html><a href=\"https://github.com/captainjack64/hacktv\">https://github.com/captainjack64/hacktv</a></html>");
        lblCaptainJack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaptainJack2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCaptainJack2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCaptainJack2MouseExited(evt);
            }
        });

        lblinaxeon1.setText("<html>A fork of fsphil's build with support for genuine Philips test signals.<br>Ideal for equipment testing.</html>");

        lblinaxeon2.setText("<html><a href=\"https://github.com/inaxeon/hacktv\">https://github.com/inaxeon/hacktv</a></html>");
        lblinaxeon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinaxeon2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblinaxeon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblinaxeon2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout downloadPanelLayout = new javax.swing.GroupLayout(downloadPanel);
        downloadPanel.setLayout(downloadPanelLayout);
        downloadPanelLayout.setHorizontalGroup(
            downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadPanelLayout.createSequentialGroup()
                .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnfsphil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfsphil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfsphil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnCaptainJack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCaptainJack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaptainJack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btninaxeon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinaxeon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblinaxeon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        downloadPanelLayout.setVerticalGroup(
            downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnfsphil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addComponent(lblfsphil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfsphil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaptainJack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCaptainJack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaptainJack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(downloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btninaxeon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(downloadPanelLayout.createSequentialGroup()
                        .addComponent(lblinaxeon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblinaxeon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downloadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downloadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void download(int fork) {
        // Downloads the latest pre-compiled Windows build from my build server
        switch (fork) {
            case 0:
                // fsphil download
                selection = "https://download.bops.ie/hacktv/fsphil.zip";
                break;
            case 1:
                // Captain Jack download
                selection = "https://download.bops.ie/hacktv/captainjack.zip";
                break;
            case 2:
                // Matts TV Barn (inaxeon)
                selection = "https://download.bops.ie/hacktv/mattstvbarn.zip";
                break;
            default:
                break;
        }
        this.dispose();
    }
    
    public String getSelection() {
        return selection;
    }
    
    private void lblinaxeon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinaxeon2MouseClicked
        try {
            new Shared().launchBrowser(lblinaxeon2.getText().split("\"(.*?)")[1]);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null ,"Unable to launch default browser.", GUI.APP_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblinaxeon2MouseClicked

    private void lblinaxeon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinaxeon2MouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblinaxeon2MouseEntered

    private void lblinaxeon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinaxeon2MouseExited
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblinaxeon2MouseExited

    private void lblfsphil2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfsphil2MouseClicked
        try {
            new Shared().launchBrowser(lblfsphil2.getText().split("\"(.*?)")[1]);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null ,"Unable to launch default browser.", GUI.APP_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblfsphil2MouseClicked

    private void lblfsphil2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfsphil2MouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblfsphil2MouseEntered

    private void lblfsphil2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfsphil2MouseExited
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblfsphil2MouseExited

    private void lblCaptainJack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaptainJack2MouseClicked
        try {
            new Shared().launchBrowser(lblCaptainJack2.getText().split("\"(.*?)")[1]);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null ,"Unable to launch default browser.", GUI.APP_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblCaptainJack2MouseClicked

    private void lblCaptainJack2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaptainJack2MouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCaptainJack2MouseEntered

    private void lblCaptainJack2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaptainJack2MouseExited
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblCaptainJack2MouseExited

    private void btnfsphilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfsphilActionPerformed
        download(0);
    }//GEN-LAST:event_btnfsphilActionPerformed

    private void btnCaptainJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptainJackActionPerformed
        download(1);
    }//GEN-LAST:event_btnCaptainJackActionPerformed

    private void btninaxeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninaxeonActionPerformed
        download(2);
    }//GEN-LAST:event_btninaxeonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaptainJack;
    private javax.swing.JButton btnfsphil;
    private javax.swing.JButton btninaxeon;
    private javax.swing.JPanel downloadPanel;
    private javax.swing.JLabel lblCaptainJack1;
    private javax.swing.JLabel lblCaptainJack2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblfsphil1;
    private javax.swing.JLabel lblfsphil2;
    private javax.swing.JLabel lblinaxeon1;
    private javax.swing.JLabel lblinaxeon2;
    // End of variables declaration//GEN-END:variables
}
