[Modes.ini]
FileVersion=6.0

; This section is deprecated and no longer used
; Currently retained for backwards compatibility but will be removed in a future release
[videomodes]
pal=i, g, pal-d, pal-fm, pal-n, pal-m, pal60-i, pal, pal60, 525pal
ntsc=m, ntsc-fm, ntsc-bs, ntsc-i, ntsc-a, apollo-fsc-fm, m-cbs405, ntsc, ntsc-405, cbs405, apollo-fsc
secam=l, d, secam-b, secam-fm, secam-i, secam
other=a, e, 240-am, 30-am, apollo-fm, nbtv-am, 405-i, 405, 819, 240, 30, apollo, nbtv
mac=d2mac-fm, dmac-fm, d2mac-am, dmac-am, d2mac, dmac

[videocrypt]
free=Free access/soft scrambled (no card required)
conditional=Conditional access (Sky 11 card)

[videocrypt2]
free=Free access/soft scrambled (no card required)

[videocrypts]
free=Free access/soft scrambled (no card required)
conditional=Conditional access (BBC Select card)

[syster]
premiere-fa=Free access (Premiere Germany)
premiere-ca=Conditional access (Premiere Germany)
cfrfa=Free access (Canal+ France)
cfrca=Conditional access (Canal+ France)
cplfa=Free access (Canal+ Poland)
cesfa=Free access (Canal+ Spain)
chorfa=Free access (Canal+ Horizons)
ntvfa=Free access (HTB+ Russia)

[eurocrypt]
; The "blank" parameter is deprecated and no longer used
; Currently retained for backwards compatibility but will be removed in a future release
blank=No conditional access (free)
bbcprime=EuroCrypt M (BBC Prime)
cplusfr=EuroCrypt M (Canal+ France 4:3)
cplusfr169=EuroCrypt M (Canal+ France 16:9)
ctv=EuroCrypt M (CTV)
filmnet=EuroCrypt M (FilmNet)
multivisio=EuroCrypt M (Multivisio)
tv3=EuroCrypt M (TV3)
tv1000=EuroCrypt M (TV 1000)
tvcable=EuroCrypt M (TV Cable)
tvplus=EuroCrypt M (TVPlus)
visiopass=EuroCrypt M (Visiopass)
teletv=EuroCrypt S (Tele-TV)
ctvs=EuroCrypt S2 (CTV)
eros=EuroCrypt S2 (Eros)
nrk=EuroCrypt S2 (NRK)
rdv=EuroCrypt S2 (RDV)
tv2=EuroCrypt S2 (TV2 Norway)
tvs=EuroCrypt S2 (TV-S)
cplus=EuroCrypt 3DES (Canal+ Denmark)

[testsignals_625_pal]
; The syntax of this section is as follows:
; Command line argument=Friendly name, pattern filename, text insertion supported, sample rate
; Sample rate defaults to 13.5 MHz if not defined
colourbars=hacktv colour bars
cbar=EBU colour bars,ebu_cbar_pal.bin,0
philips4x3=Philips 4:3,philips_4x3_pal.bin,1
philips16x9=Philips 16:9,philips_16x9_pal.bin,1
fubk4x3=FuBK 4:3,fubk_4x3.bin,1
fubk16x9=FuBK 16:9,fubk_16x9_pal.bin,1
philipsih=Indian Head,philips_indian_head.bin,0,20
pulseandbar=Pulse and bar,pulse_bar_pal.bin,0
sinxx=Sinx/x,sin_x_x_pal.bin,0

[testsignals_525_ntsc]
colourbars=hacktv colour bars
cbar=SMPTE bars,smtpe_cbar_ntsc.bin,1
philips4x3=Philips 4:3,philips_4x3_ntsc.bin,1
philips16x9=Philips 16:9,philips_16x9_ntsc.bin,1

[testsignals_625_secam]
colourbars=hacktv colour bars
philips4x3=Philips 4:3,philips_4x3_secam.bin,1

; PAL
[i]
name=PAL-I
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
audiosubcarrier=5999600
sr=15000000
colour=1
colourmode=pal
audio=1
nicam=1
a2stereo=1
defaultstereo=nicam
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
vhf=vhf_ie
vhf2=vhf_za

[g]
alt=b
name=PAL-B/G
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
audiosubcarrier=5500000
sr=15000000
colour=1
colourmode=pal
audio=1
nicam=1
a2stereo=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
uhf2=uhf_au
uhf3=uhf_nz
vhf=vhf_eu
vhf2=vhf_au
vhf3=vhf_nz

[pal-d]
alt=pal-k
name=PAL-D/K
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
audiosubcarrier=6500000
sr=15000000
colour=1
colourmode=pal
audio=1
nicam=1
a2stereo=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_cn
vhf=vhf_cn
; Compatible for OIRT countries that have moved from SECAM-D/K to PAL-D/K
uhf2=uhf_eu
vhf2=vhf_ru

[pal-fm]
name=PAL-FM
lines=625
fieldrate=50
modulation=fm
audiomodulation=fm
sr=20250000
colour=1
colourmode=pal
audio=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1
sat=astra

[pal-m]
name=PAL-M
lines=525
fieldrate=59.94
modulation=vsb
audiomodulation=fm
audiosubcarrier=4500000
sr=13500000
colour=1
colourmode=pal
audio=1
uhf=uhf_ntsc
vhf=vhf_ntsc

[pal-n]
name=PAL-N
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
audiosubcarrier=4500000
sr=13500000
colour=1
colourmode=pal
audio=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_ntsc
vhf=vhf_ntsc

[pal60-i]
; Non-standard PAL/525 with System I audio spacing
name=PAL60-I
lines=525
fieldrate=59.94
audiomodulation=fm
audiosubcarrier=5999600
modulation=vsb
sr=13500000
colour=1
colourmode=pal
audio=1
uhf=uhf_eu
vhf=vhf_ie
description=Non-standard PAL/525 with System I audio spacing

[pal]
name=PAL 625 (unmodulated)
lines=625
fieldrate=50
modulation=baseband
sr=13500000
colour=1
colourmode=pal
teletext=1
wss=1
vits=1
acp=1
scrambling=1

[pal60]
name=PAL 525 (unmodulated)
lines=525
modulation=baseband
sr=13500000
colour=1
colourmode=pal
description=Baseband PAL 525/60 with standard 4.433618 MHz colour subcarrier

[525pal]
name=PAL 525 (Brazil, unmodulated)
lines=525
fieldrate=59.94
modulation=baseband
sr=13500000
colour=1
colourmode=pal
description=Baseband PAL 525/60 with Brazilian standard colour subcarrier

; NTSC
[m]
name=NTSC-M
lines=525
fieldrate=59.94
modulation=vsb
audiomodulation=fm
audiosubcarrier=4500000
sr=13500000
colour=1
colourmode=ntsc
audio=1
audiosubcarrier=4500000
a2stereo=1 ; Korean variant
defaultstereo=none
uhf=uhf_ntsc
vhf=vhf_ntsc
uhf2=uhf_jp
vhf2=vhf_jp

[ntsc-fm]
name=NTSC-FM
lines=525
fieldrate=59.94
modulation=fm
audiomodulation=fm
sr=18000000
colour=1
colourmode=ntsc
audio=1

[ntsc-bs]
name=NTSC-FM BS
lines=525
fieldrate=59.94
modulation=fm
audiomodulation=digital
sr=18000000
colour=1
colourmode=ntsc
audio=1
description=BS digital audio as used on Japanese satellite services

[ntsc-i]
name=NTSC-I
nonstandard=1
lines=525
fieldrate=59.94
modulation=vsb
audiomodulation=fm
audiosubcarrier=5999600
sr=13500000
colour=1
colourmode=ntsc
audio=1
uhf=uhf_eu
vhf=vhf_ie
vhf2=vhf_za
description=Non-standard NTSC/525 with System I audio spacing

[ntsc-a]
name=NTSC-A
lines=405
fieldrate=50
modulation=vsb
audiomodulation=am
audiosubcarrier=-3500000
sr=8100000
colour=1
colourmode=ntsc
audio=1
vhf=vhf_gb
description=NTSC-A based on the 1954 Marconi proposal<br>Was not used except for early BBC tests

[ntsc]
name=NTSC 525 (unmodulated)
lines=525
fieldrate=59.94
modulation=baseband
sr=13500000
colour=1
colourmode=ntsc

[ntsc-405]
; Baseband version of NTSC-A
name=NTSC 405 (unmodulated)
lines=405
fieldrate=50
modulation=baseband
sr=8100000
colour=1
colourmode=ntsc

; SECAM
[l]
name=SECAM-L
lines=625
fieldrate=50
modulation=vsb
audiomodulation=am
sr=15000000
colour=1
colourmode=secam
audio=1
audiosubcarrier=6500000
nicam=1
a2stereo=0
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
vhf=vhf_fr_l

[d]
alt=k
name=SECAM-D/K
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
sr=15000000
colour=1
colourmode=secam
audio=1
audiosubcarrier=6500000
nicam=0
a2stereo=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
vhf=vhf_ru

[secam-b]
alt=secam-g
name=SECAM-B/G
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
sr=15000000
colour=1
colourmode=secam
audio=1
audiosubcarrier=5500000
nicam=1
a2stereo=0
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
vhf=vhf_eu

[secam-fm]
name=SECAM-FM
lines=625
fieldrate=50
modulation=fm
sr=20250000
colour=1
colourmode=secam
audio=1
teletext=1
wss=1
vits=1
acp=1
scrambling=1

[secam-i]
name=SECAM-I
nonstandard=1
lines=625
fieldrate=50
modulation=vsb
audiomodulation=fm
sr=15000000
colour=1
colourmode=secam
audio=1
audiosubcarrier=5999600
nicam=1
a2stereo=0
teletext=1
wss=1
vits=1
acp=1
scrambling=1
uhf=uhf_eu
vhf=vhf_ie

[secam]
name=SECAM 625 (unmodulated)
lines=625
modulation=baseband
sr=13500000
colour=1
colourmode=secam
teletext=1
wss=1
vits=1
acp=1
scrambling=1

; Monochrome modes
[a]
name=A (405 lines)
lines=405
fieldrate=50
modulation=vsb
audiomodulation=am
sr=8100000
audio=1
audiosubcarrier=-3500000
colourmode=none
vhf=vhf_gb

[e]
name=E (819 lines)
lines=819
fieldrate=50
modulation=vsb
audiomodulation=am
sr=20250000
audio=1
audiosubcarrier=11150000
colourmode=none
vhf=vhf_fr_e

[240-am]
name=Baird mechanical (240/25)
lines=240
fieldrate=50
modulation=vsb
sr=1992000
colourmode=none

[30-am]
name=Baird mechanical (30/12.5)
lines=30
fieldrate=25
modulation=vsb
sr=100500
colourmode=none

[apollo-fm]
name=Apollo FM (320/10)
lines=320
fieldrate=20
modulation=fm
sr=2480000
colourmode=none

[nbtv-am]
name=NBTV Club standard
lines=32
fieldrate=25
modulation=vsb
sr=100000
colourmode=none

[405-i]
; Non-standard 405 line variant, negatively modulated with System I-style FM audio carrier
; This was never used but works on Sony TV9-90UB sets with both VHF and UHF buttons pressed in
; Since this mode switches the tuner to UHF, we'll only enable the European UHF bandplan
name=405-I
nonstandard=1
lines=405
fieldrate=50
modulation=vsb
audiomodulation=fm
audiosubcarrier=5999600
sr=8100000
audio=1
colourmode=none
uhf=uhf_eu
description=Negatively modulated 405 lines with System I-style FM audio carrier<br>Works on Sony TV9-90UB sets with both VHF and UHF buttons pressed in<br>UHF only

[405]
name=405 (unmodulated)
lines=405
fieldrate=50
modulation=baseband
sr=8100000
colourmode=none

[819]
name=819 (unmodulated)
lines=819
fieldrate=50
modulation=baseband
sr=20250000
colourmode=none

[240]
name=Baird 240 (unmodulated)
lines=240
fieldrate=50
modulation=baseband
sr=1992000
colourmode=none

[30]
name=Baird 30 (unmodulated)
lines=30
fieldrate=25
modulation=baseband
sr=100500
colourmode=none

[apollo]
name=Apollo (unmodulated)
lines=320
fieldrate=20
modulation=baseband
sr=2480000
colourmode=none

[nbtv]
name=NBTV Club (unmodulated)
lines=32
fieldrate=25
modulation=baseband
sr=100000
colourmode=none

; MAC
[d2mac-am]
name=D2-MAC (AM)
lines=625
fieldrate=50
modulation=vsb
audiomodulation=digital
sr=20250000
colourmode=mac
audio=1
teletext=1
scrambling=1

[d2mac-fm]
name=D2-MAC (FM)
lines=625
fieldrate=50
modulation=fm
audiomodulation=digital
sr=20250000
colourmode=mac
audio=1
teletext=1
scrambling=1

[dmac-am]
name=D-MAC (AM)
lines=625
fieldrate=50
modulation=vsb
audiomodulation=digital
sr=20250000
colourmode=mac
audio=1
teletext=1
scrambling=1

[dmac-fm]
name=D-MAC (FM)
lines=625
fieldrate=50
modulation=fm
audiomodulation=digital
sr=20250000
colourmode=mac
audio=1
teletext=1
scrambling=1
sat=bsb

[d2mac]
name=D2-MAC (unmodulated)
lines=625
fieldrate=50
modulation=baseband
sr=20250000
colourmode=mac
teletext=1
scrambling=1

[dmac]
name=D-MAC (unmodulated)
lines=625
fieldrate=50
modulation=baseband
sr=20250000
colourmode=mac
teletext=1
scrambling=1

; Modes which don't belong in the other categories
[m-cbs405]
name=CBS Field Sequential Color
lines=405
fieldrate=144
modulation=vsb
audiomodulation=fm
audiosubcarrier=4500000
sr=18954000
colour=1
colourmode=other
audio=1
uhf=uhf_ntsc
vhf=vhf_ntsc

[cbs405]
name=CBS FSC (unmodulated)
lines=405
fieldrate=144
modulation=baseband
sr=18954000
colour=1
colourmode=other

[apollo-fsc-fm]
name=Apollo Field Sequential Color (FM)
lines=525
fieldrate=59.94
modulation=fm
sr=18000000
colour=1
colourmode=other
audio=1
description=Apollo Field Sequential Color

[apollo-fsc]
name=Apollo FSC (unmodulated)
lines=525
fieldrate=59.94
modulation=baseband
sr=18000000
colour=1
colourmode=other
description=Apollo Field Sequential Color
