/*
 * Copyright (C) 2026 Stephen McGarry
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package ie.bops.hacktvgui;

import java.util.Locale;
import javax.swing.JOptionPane;


public class MacSettingsDialogue extends javax.swing.JDialog {
    
    private MacSettings settings;
    
    public MacSettingsDialogue(java.awt.Frame parent, boolean modal, MacSettings s) {
        super(parent, modal);
        initComponents();
        settings = s;
    }
    
    public void postInit() {
        if (settings == null) return;
        String chid = settings.channelID();
        if (chid == null || chid.isBlank()) {
            if (chkChId.isSelected()) chkChId.doClick();
        } else {
            if (!chkChId.isSelected()) chkChId.doClick();
            txtMacChId.setText(chid);
        }
        chkAudioMode.setSelected(settings.audioMode());
        chkAudioQuality.setSelected(settings.audioQuality());
        chkAudioCompression.setSelected(settings.audioCompression());
        chkAudioProtection.setSelected(settings.audioProtection());
    }
    
    private String checkMacChId(String input) {
        if (chkChId.isSelected()) {
            if (Shared.isHex(input)) {
                return input;
            } else {
                Shared.messageBox("Please specify a valid hexadecimal channel ID.", JOptionPane.WARNING_MESSAGE);
                return null;
            }
        } else {
            // Return an empty string because null is indicative of an error condition
            return "";
        }
    }
    
    public MacSettings getSettings() {
        return settings;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        macPanel = new javax.swing.JPanel();
        chkChId = new javax.swing.JCheckBox();
        txtMacChId = new javax.swing.JTextField();
        chkAudioMode = new javax.swing.JCheckBox();
        chkAudioQuality = new javax.swing.JCheckBox();
        chkAudioCompression = new javax.swing.JCheckBox();
        chkAudioProtection = new javax.swing.JCheckBox();
        buttonPanel = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAC options");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        macPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("MAC options"));
        macPanel.setLayout(new java.awt.GridBagLayout());

        chkChId.setText("Override channel ID");
        chkChId.addActionListener(this::chkChIdActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        macPanel.add(chkChId, gridBagConstraints);

        txtMacChId.setEditable(false);
        txtMacChId.setEnabled(false);
        txtMacChId.addMouseListener(new ContextMenuListener());
        txtMacChId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMacChIdKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        macPanel.add(txtMacChId, gridBagConstraints);

        chkAudioMode.setText("Mono audio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        macPanel.add(chkAudioMode, gridBagConstraints);

        chkAudioQuality.setText("16 kHz audio sample rate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        macPanel.add(chkAudioQuality, gridBagConstraints);

        chkAudioCompression.setText("Linear audio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        macPanel.add(chkAudioCompression, gridBagConstraints);

        chkAudioProtection.setText("Level 2 audio protection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        macPanel.add(chkAudioProtection, gridBagConstraints);

        getContentPane().add(macPanel);

        btnOK.setText("OK");
        btnOK.addActionListener(this::btnOKActionPerformed);
        buttonPanel.add(btnOK);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        buttonPanel.add(btnCancel);

        getContentPane().add(buttonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkChIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChIdActionPerformed
        boolean b = chkChId.isSelected();
        txtMacChId.setEnabled(b);
        txtMacChId.setEditable(b);
        if (!b) txtMacChId.setText("");
    }//GEN-LAST:event_chkChIdActionPerformed

    private void txtMacChIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMacChIdKeyTyped
        if (txtMacChId.getText().length() >= 4) {
            evt.consume();
        } else {
            String c = String.valueOf(evt.getKeyChar());
            if (Shared.isHex(c)) {
                evt.setKeyChar(c.toUpperCase(Locale.ENGLISH).toCharArray()[0]);
            } else {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtMacChIdKeyTyped

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String chid = checkMacChId(txtMacChId.getText());
        if (chid == null) return;
        settings = new MacSettings(
                chid,
                chkAudioMode.isSelected(),
                chkAudioQuality.isSelected(),
                chkAudioCompression.isSelected(),
                chkAudioProtection.isSelected()
        );
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox chkAudioCompression;
    private javax.swing.JCheckBox chkAudioMode;
    private javax.swing.JCheckBox chkAudioProtection;
    private javax.swing.JCheckBox chkAudioQuality;
    private javax.swing.JCheckBox chkChId;
    private javax.swing.JPanel macPanel;
    private javax.swing.JTextField txtMacChId;
    // End of variables declaration//GEN-END:variables
}
